### ISSUE TITLE
invalid syntax in `*ind_agg`

### ISSUE THREAD

**Issue by alecomunian** [randlab/geone#15]
Hello Julien,

I experienced a `invalid syntax`  problem with the last version of `geone`. I've tried a quick comparison with the previous version, but I find it a little hard at a first sight to pin the error. Do you have some suggestion?

The error that I get (installing with the standard procedure `geone` in a clean virtual environment with Python 3.10.12, and running an `import geone` outside the installation folder...) is the following:

> 
> import geone
> Traceback (most recent call last):
> 
>   File ~/.virtualenvs/test_geone/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3553 in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   Cell In[15], line 1
>     import geone
> 
>   File ~/.virtualenvs/test_geone/lib/python3.10/site-packages/geone/__init__.py:9
>     from . import geosclassicinterface
> 
>   File ~/.virtualenvs/test_geone/lib/python3.10/site-packages/geone/geosclassicinterface.py:1676
>     x_agg = im_tmp.xx()[*ind_agg].reshape(-1, 1)
>                                          ^
> SyntaxError: invalid syntax
> 
> 

It seems that is does not like the asterisk in `*ind_agg`.

Thank you in advance and happy new year!

Alessandro

**Comment by julien-straubhaar** [comment]
Hello Alessandro,
Thank you for your post. I think that I fixed the problem, now it should work with python 3.10 too.

Happy new year, and best wishes
Julien

**Comment by alecomunian** [comment]
Thank you very much Julien, that worked fine!
